<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select ConsumptionGender as label, SugarIntake as y
from (select State, Year as ConsumptionYear, Gender as ConsumptionGender, SugarIntake
      from ConsumptionStats left join Location Loc on Loc.LocationID = ConsumptionStats.LocationID
      where State='California' and ConsumptionStats.AgeRange='18+') as CL;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Unable to get sugar intake for this data!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
