<?php

if(ISSET($_POST['getStats'])){
    $sf = $_POST['sfFilter'];
    if ($stmt = $conn->prepare("
		(SELECT State
                FROM    (SELECT State, AVG(numStudents) as avgStudents
                        FROM SchoolFoodPrograms NATURAL JOIN Location
                        WHERE Name = '$sf'
                        GROUP BY State
                        ORDER BY avgStudents DESC
                        LIMIT 1) as maxStudentState);

	")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Could not find state with highest school food program enrollment.<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
