<?php
GLOBAL $selectedState;

if(ISSET($_POST['getStats'])){
    $year=$_POST['yearFilter'];

    /*echo $name;*/

    if ($stmt = $conn->prepare("select ((numEnrolled/Total) * 100) as y, Name as legendText, Name as label from (SELECT Name,numEnrolled from FoodAssistance left join Location on FoodAssistance.locationID=Location.locationID WHERE Year='$year' and State='$selectedState' group by Name) as sum,(SELECT SUM(numEnrolled) as Total from FoodAssistance left join Location on FoodAssistance.locationID=Location.locationID WHERE Year='$year' and State='$selectedState' group by year) as Total;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                /*error handling here is already matched in chart 1 filter!*/
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}

