<?php

if(ISSET($_POST['addInfo'])){
    $State = $_POST['givenState'];
    $County = $_POST['givenCounty'];
    $City = $_POST['givenCity'];

    //state cannot be empty when inserting data. We will tolerate not having counties for special zones like reservations
    if($State == null){
        echo "<br>ERROR: State field cannot be empty!<br>";
    } else if(($State != null) && (($County == null) && ($City != null))){
        echo "<br>ERROR: To specify a city, please specify the county that city resides in!!<br>";
    } else if($stmt = $conn->prepare("call deleteLocationByNames('$State', '$County', '$City')")){

        #echo "<br>INFO: Adding data!<br>";

        if ($stmt->execute()) {

            #echo "<br>INFO: executed!<br>";

            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows > 0) {

                echo "<br>ERROR: something went wrong.<br>";
            } else {


                #echo "<br>INFO: That location does not exist!<br>";


            }
        }

        $result->free_result();

    }  else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();


}
