<?php

if(ISSET($_POST['addInfo'])){
    $State = $_POST['stateFilter'];
    $Name = $_POST['nameFilter'];
    $Year = $_POST['givenYear'];

    if(empty($State) || empty($Name) || empty($Year)){
        echo "<br>ERROR: Please fill in all required fields!";
    } else if((! ctype_digit(strval($Year)))){
        echo "<br>ERROR: Please enter the year in integer form!";
    } else if($stmt = $conn->prepare("call deleteFA('$State', '$Name', '$Year')")){

        #echo "<br>INFO: Adding data!<br>";

        if ($stmt->execute()) {

            #echo "<br>INFO: executed!<br>";

            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows > 0) {

                echo "<br>ERROR: That FA data does not exist!<br>";
            } else {

                echo "<br>That FA data has been deleted!<br>";


            }
        }

        $result->free_result();

    }  else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();


}
