<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select FoodAssistanceSummed.State, FoodAssistanceSummed.Year, MAX(FoodAssistanceSummed.sumEnrolled) as 'FA',
       (select SUM(numStudents) as 'sumStudents'
        from SchoolFoodPrograms left join Location on SchoolFoodPrograms.locationID=Location.locationID
        where Year=FoodAssistanceSummed.Year and State=FoodAssistanceSummed.State
        Group by year, State
        order by sumStudents DESC) as 'SFP'
from (select State, Year, SUM(numEnrolled) as 'sumEnrolled'
      from FoodAssistance left join Location on FoodAssistance.locationID=Location.locationID
      Group by year, State
      Order By sumEnrolled DESC) as FoodAssistanceSummed;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: No available food assistance/SFP data for this selection.<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
