<?php
GLOBAL $selectedState;
GLOBAL $selectedCounty;


if ($stmt = $conn->prepare("select distinct City from Location where State='$selectedState' and County='$selectedCounty';")) {
    if ($stmt->execute()) {
        //Store result set generated by the prepared statement
        $result = $stmt->get_result();

        $stmt->close();
        return $result;
        //error handling will be done in main file.
    } else {
        //Call to execute failed, e.g. because server is no longer reachable,
        //or because supplied values are of the wrong type
        echo "<br>ERROR: Execute failed.<br>";
    }
} else {

    //A problem occurred when preparing the statement; check for syntax errors
    //and misspelled attribute names in the statement string.

    echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
}

$stmt->close();