<?php

if(ISSET($_POST['addInfo'])){
    $State = $_POST['givenState'];
    $County = $_POST['givenCounty'];
    $City = $_POST['givenCity'];

    //state cannot be empty when inserting data. We will tolerate not having counties for special zones like reservations
    if($State == null){
        echo "<br>ERROR: State field cannot be empty!<br>";
    } else if($stmt = $conn->prepare("SELECT * FROM Location WHERE State = ? AND County = ? AND City = ?;")){

        #echo "<br>INFO: Adding data!<br>";

        $stmt->bind_param('sss', $State, $County, $City);

        if ($stmt->execute()) {

            #echo "<br>INFO: executed!<br>";

            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows > 0) {
                $stmt->close();
                $result->free_result();
                echo "<br>ERROR: That location already exists!<br>";
            } else {
                $stmt->close();
                $result->free_result();
                #echo "<br>INFO: That location does not exist!<br>";


                if ($stmt = $conn->prepare("insert into Location set State = ?, County = ?, City = ?")) {

                    $stmt->bind_param('sss', $State, $County, $City);

                    if ($stmt->execute()) {
                        //Store result set generated by the prepared statement
                        $result = $stmt->get_result();

                        if($result->num_rows != 0){
                            $result->free_result();
                            $stmt->close();

                            echo "<br>ERROR: Data insert failed! That location might already exist or is too long!<br>";
                        } else {
                            $stmt->close();
                            echo "<br>Location data added successfully!<br>";
                        }

                    } else {
                        //Call to execute failed, e.g. because server is no longer reachable,
                        //or because supplied values are of the wrong type
                        $stmt->close();
                        echo "<br>ERROR: Execute failed.<br>";
                    }

                } else {

                    //A problem occurred when preparing the statement; check for syntax errors
                    //and misspelled attribute names in the statement string.
                    $stmt->close();
                    echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
                }


            }
        }



    }  else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.
        $stmt->close();
        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }


}
