<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select State from (select State, MAX(numPassed) from (select Location.State, Count(FoodLegislation.BillName) as numPassed from FoodLegislation left join Location on FoodLegislation.LocationID=Location.LocationID group by State order by numPassed DESC) as BillCount)as stateCount")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: No states have any legislation data!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
