<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select Year, State, Max(totalSugar) as 'SugarIntake',
       (select SUM(numEnrolled)
        from FoodAssistance left join Location on FoodAssistance.LocationID = Location.LocationID
        where year=sugarIntake.Year and Location.State=sugarIntake.State
        group by year) as 'EnrollNum'
from (select Year, State, SUM(SugarIntake) as 'totalSugar'
      from ConsumptionStats left join Location on ConsumptionStats.LocationID = Location.LocationID
      where (Gender='Female' or Gender='Male')
      group by Year
      order by totalSugar DESC) as sugarIntake;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: No sugar/enrollment data available!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
