<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select SYA.Year as x, SYA.Obesity as 'y'
from (select State, Year, AVG(Obesity) as Obesity
      from MetabolicDisease left join Location L on L.LocationID = MetabolicDisease.LocationID
      where State='California' and Gender='All'
      group by Year) as SYA;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Unable to get obesity data for California!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
