<?php
GLOBAL $minYear;
GLOBAL $maxYear;

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("select (select 'Income50kTo75k') as name, Year as x, Income50kTo75k as y from AvgHousehold where (year between '$minYear' and '$maxYear') order by year;")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Unable to get data for Income50kTo75k<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
