<?php

if(ISSET($_POST['getInfo'])){

    if ($stmt = $conn->prepare("
    SELECT Year, IncomeUnder15k, Income15kTo25k, Income25kTo35k, 
    Income35kTo50k, Income50kTo75k, Income75kTo100k, Income100kTo150k, 
    Income150kTo200k, Income200kAbove, AvgIncome
        FROM AvgHousehold
        WHERE Year = '$maxYear';
    ")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: {INSERT ERROR MESSAGE HERE!}<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
