<?php

if(ISSET($_POST['getInfo'])){
	$state = $_POST['stateFilter'];

	if ($stmt = $conn->prepare("
		SELECT *
		FROM (
			SELECT State, avgObesity, minObesity, minObesityYear, maxObesity, maxObesityYear
			FROM
        			(SELECT *
        			FROM
                	(SELECT State, AVG(Obesity) AS avgObesity, MAX(Obesity) AS maxObesity, MIN(Obesity) AS minObesity
                	FROM
                	(SELECT LocationID, Year, AgeRange, Gender, Obesity
                	FROM MetabolicDisease
                	WHERE Year >= '2010' AND Year <= '2022' AND AgeRange <> 'Ages 35-64 years' AND AgeRange <> 'Ages 65+ years') AS childObesity
                	NATURAL JOIN Location
                	GROUP BY State) obesityStats
                	JOIN 
                	(SELECT Year as minObesityYear, Obesity
                	FROM MetabolicDisease
                	WHERE Year >= '2010' AND Year <= '2022' AND AgeRange <> 'Ages 35-64 years' AND AgeRange <> 'Ages 65+ years') AS allObesity
                	ON obesityStats.minObesity = allObesity.Obesity) as minObesityStats
         		JOIN
         		(SELECT Year as maxObesityYear, Obesity AS maxObesity2
         		FROM MetabolicDisease
         		WHERE Year >= '2010' AND Year <= '2022' AND AgeRange <> 'Ages 35-64 years' AND AgeRange <> 'Ages 65+ years') AS maxObesityYears
         		ON minObesityStats.maxObesity = maxObesityYears.maxObesity2
			GROUP BY avgObesity DESC, State ASC ) as selection
		WHERE State = '$state';
	")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Data not available for this state!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
