<?php

if(ISSET($_POST['getInfo'])){
	$state = $_POST['stateFilter'];

	if ($stmt = $conn->prepare("
		SELECT Year as x, AVG(Obesity) as y
		FROM       
        		(SELECT * FROM MetabolicDisease 
        		WHERE Year >= '2010' AND Year <= '2022' AND AgeRange <> 'Ages 35-64 years' AND AgeRange <> 'Ages 65+ years') as childObesity
                	NATURAL JOIN 
        		Location
		WHERE State = '$state'
		GROUP BY Year;
	")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "<br>ERROR: Obesity Data not available for this state!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "<br>ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "<br>ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}
