<?php
require '../../open.php';
if(ISSET($_POST['getStats'])){
    $name=$_POST['stateFilter'];

    /*echo $name;*/

    if ($stmt = $conn->prepare("SELECT Year as x, SUM(numStudents) as y FROM SchoolFoodPrograms left join Location on SchoolFoodPrograms.locationID=Location.locationID WHERE State='$name' group by year")) {
        if ($stmt->execute()) {
            //Store result set generated by the prepared statement
            $result = $stmt->get_result();

            if($result->num_rows < 1){
                echo "ERROR: This state has no records in our database!<br>";
            } else {
                $stmt->close();
                return $result;
            }
            $result->free_result();
        } else {
            //Call to execute failed, e.g. because server is no longer reachable,
            //or because supplied values are of the wrong type
            echo "ERROR: Execute failed.<br>";
        }
    } else {

        //A problem occurred when preparing the statement; check for syntax errors
        //and misspelled attribute names in the statement string.

        echo "ERROR: Prepare failed.<br>" . $conn->errno . ' ' . $conn->error;
    }

    $stmt->close();
}

